export enum EAuthStatus {
   IS_AUTHENTICATED = "IS_AUTHENTICATED",
   UNAUTHENTICATED = "UNAUTHENTICATED",
   UNKNOWN = "UNKNOWN",
}

export enum EProjectRoles {
   ADMIN = "PROJECT_ROLE_ADMIN",
   LEADER = "PROJECT_ROLE_LEADER",
   MEMBER = "PROJECT_ROLE_MEMBER",
}

export enum EUserRoles {
   ADMIN = "USER_ROLE_ADMIN",
   USER = "USER_ROLE_USER",
}
