export enum EAuthStatus {
   IS_AUTHENTICATED = "IS_AUTHENTICATED",
   UNAUTHENTICATED = "UNAUTHENTICATED",
   UNKNOWN = "UNKNOWN",
}

export enum EUserRoles {
   ADMIN = "USER_ROLE_ADMIN",
   LEADER = "USER_ROLE_LEADER",
   MEMBER = "USER_ROLE_MEMBER",
}
